Cumulus 2524 - CSS Tweaks
nasa/cumulus-dashboard pull request #966
Opened 2021-05-27 21:09 UTC by jjmccoy

**Summary:** Summary of changes

Addresses [CUMULUS-2524: CSS Tweaks](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2524)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

2021-06-02 22:03 UTC, flamingbear requested changes
Looks good, but I have a question about the button.scss and the multiple ways that &--close and &--show are defined.  If you can clean that up into a single thing, everything else look great.

2021-06-02 22:54 UTC, jjmccoy commented on app/src/css/_buttons.scss
> +  &--close, &--show {
@flamingbear Thanks. So the padding makes the size styling of the button and the margin is the space between the button and other objects on the page. Hope that makes sense.

2021-06-03 14:07 UTC, flamingbear commented on app/src/css/_buttons.scss
> +  &--close, &--show {
Not me, reading padding and seeing margin.  Thanks.

2021-06-03 14:07 UTC, flamingbear approved these changes

2021-06-03 16:23 UTC, merged